from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


_DESCRIBE_RE = re.compile(
    r"^(?P<tag>.+)-(?P<count>\d+)-g(?P<commit>[0-9a-f]+)(?P<dirty>-dirty)?$",
    re.IGNORECASE,
)
_SEMVER_RE = re.compile(r"^v?(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)$")


@dataclass(frozen=True)
class BuildVersion:
    source_tag: str
    commits_since_tag: int
    commit: str
    dirty: bool
    major: int
    minor: int
    patch: int

    @property
    def display_version(self) -> str:
        suffix = "-dirty" if self.dirty else ""
        return f"v{self.major}.{self.minor}.{self.patch} ({self.commit}{suffix})"

    @property
    def numeric_version(self) -> str:
        return f"{self.major}.{self.minor}.{self.patch}.0"

    @property
    def numeric_tuple(self) -> tuple[int, int, int, int]:
        return (self.major, self.minor, self.patch, 0)

    @property
    def describe(self) -> str:
        dirty_suffix = "-dirty" if self.dirty else ""
        return f"{self.source_tag}-{self.commits_since_tag}-g{self.commit}{dirty_suffix}"


def _run_git(repo_root: Path, args: list[str]) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=str(repo_root),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        message = (result.stderr or result.stdout or "").strip()
        raise RuntimeError(message or f"git {' '.join(args)} failed")
    return result.stdout.strip()


def derive_build_version(repo_root: Path) -> BuildVersion:
    describe = _run_git(
        repo_root,
        [
            "describe",
            "--tags",
            "--long",
            "--dirty",
            "--match",
            "v[0-9]*",
            "--match",
            "[0-9]*",
        ],
    )
    match = _DESCRIBE_RE.match(describe)
    if not match:
        raise RuntimeError(f"git describe output is not tag-based: {describe!r}")

    source_tag = match.group("tag")
    semver = _SEMVER_RE.match(source_tag)
    if not semver:
        raise RuntimeError(f"latest reachable tag is not a semantic version: {source_tag!r}")

    commits_since_tag = int(match.group("count"))
    major = int(semver.group("major"))
    minor = int(semver.group("minor"))
    patch = int(semver.group("patch")) + commits_since_tag
    return BuildVersion(
        source_tag=source_tag,
        commits_since_tag=commits_since_tag,
        commit=match.group("commit"),
        dirty=bool(match.group("dirty")),
        major=major,
        minor=minor,
        patch=patch,
    )


def write_build_info_module(path: Path, version: BuildVersion) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(
        [
            "# Generated by tools/generate_build_metadata.py.",
            "DISPLAY_VERSION = " + repr(version.display_version),
            "NUMERIC_VERSION = " + repr(version.numeric_version),
            "SOURCE_TAG = " + repr(version.source_tag),
            "COMMITS_SINCE_TAG = " + repr(version.commits_since_tag),
            "COMMIT = " + repr(version.commit),
            "DIRTY = " + repr(version.dirty),
            "GIT_DESCRIBE = " + repr(version.describe),
            "",
        ]
    )
    path.write_text(content, encoding="utf-8")


def write_pyinstaller_version_file(path: Path, version: BuildVersion, exe_name: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    filevers = version.numeric_tuple
    product_name = "Windows Supporter"
    content = f"""# Generated by tools/generate_build_metadata.py.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers!r},
    prodvers={filevers!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'ePapyrus'),
          StringStruct('FileDescription', {product_name!r}),
          StringStruct('FileVersion', {version.numeric_version!r}),
          StringStruct('InternalName', 'windows-supporter'),
          StringStruct('OriginalFilename', {exe_name!r}),
          StringStruct('ProductName', {product_name!r}),
          StringStruct('ProductVersion', {version.numeric_version!r}),
          StringStruct('Comments', {version.display_version!r}),
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    path.write_text(content, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate build-time version metadata.")
    parser.add_argument("--repo-root", default=".", help="Repository root used for Git commands.")
    parser.add_argument("--module-output", required=True, help="Generated build-info module path.")
    parser.add_argument("--version-file", required=True, help="Generated PyInstaller version file path.")
    parser.add_argument("--exe-name", default="windows-supporter.exe", help="Original executable filename.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(list(sys.argv[1:] if argv is None else argv))
    repo_root = Path(args.repo_root).resolve()
    try:
        version = derive_build_version(repo_root)
    except Exception as exc:
        print(f"Failed to derive tag-based build version: {exc}", file=sys.stderr)
        return 1

    module_output = Path(args.module_output)
    version_file = Path(args.version_file)
    write_build_info_module(module_output, version)
    write_pyinstaller_version_file(version_file, version, str(args.exe_name))
    print(f"Generated build metadata: {version.display_version} / {version.numeric_version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
